site_name: 'PixelView Blog'
site_url: https://blog.pixelvirt.com

theme:
  logo: images/logo.png
  favicon: images/favicon.ico
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.prune
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  copyright: Copyright &copy; 2024 Pixelvirt Technology Pvt Ltd

extra_css:
  - stylesheets/extra.css

nav:
  - Welcome: index.md
  
  - Blogs:
      - Blog: 
          - blog/index.md
  - Docs: https://docs.pixelvirt.com
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - blog:
      post_slugify_separator: _
      categories_name: Categories
      categories_url_format: "category/{slug}"
      # authors_profiles_pagination: false
      # authors_profiles: true
      categories: true
      categories_toc: true
