---
authors:
  sulochan:
    name: Sulochan M Acharya
    description: Cloud Architect @ Rackspace Technology
    avatar: https://avatars.githubusercontent.com/sulochan
    github: sulochan
    twitter: sulo
    linkedin: sulochan
  shreeraj:
    name: Shreeraj Sapkota
    description: Cloud Engineer @ Pixelvirt Technology
    avatar: https://avatars.githubusercontent.com/u/37511243?v=4
    github: shreeraj
    linkedin: shreeraj
